import { execSync } from "child_process";
import { existsSync, readFileSync } from "fs";
import { join } from "path";

/**
 * Execute Python backend inference and return the generated omnispectrum data
 */
export async function runBackendInference(): Promise<any> {
  try {
    const backendPath = join(process.cwd(), "..", "..", "omnispectrum-backend");
    
    if (!existsSync(backendPath)) {
      console.warn("⚠️ Backend directory not found. Using cached data.");
      return null;
    }

    console.log("🔄 Running backend inference...");
    
    // Run the Python inference script
    const output = execSync(`cd "${backendPath}" && python -m src.inference`, {
      encoding: "utf-8",
      stdio: "pipe",
      timeout: 60000, // 60 second timeout
    });

    console.log("Backend output:", output);

    // Read the generated JSON
    const outputPath = join(backendPath, "data", "omnispectrum.json");
    if (existsSync(outputPath)) {
      const data = readFileSync(outputPath, "utf-8");
      return JSON.parse(data);
    }

    return null;
  } catch (error) {
    console.error("⚠️ Backend inference failed:", error instanceof Error ? error.message : error);
    return null;
  }
}

/**
 * Get omnispectrum data - tries backend first, falls back to cached data
 */
export function getOmnispectrumData(cachedDataPath: string): any {
  try {
    // First try to read from the data file (could be generated by backend)
    if (existsSync(cachedDataPath)) {
      const data = readFileSync(cachedDataPath, "utf-8");
      return JSON.parse(data);
    }
  } catch (error) {
    console.error("Error reading omnispectrum data:", error);
  }

  return null;
}
